packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  workerd: true

updateNotifier: false
storeDir: "/Users/eugenezhou/Code/cipher-party/.pnpm-store"
patchedDependencies:
  "@cloudflare/vitest-plugin": patches/@cloudflare__vitest-plugin.patch
